### ISSUE TITLE
getDashboard returns an 500 internal server error

### ISSUE THREAD

**Issue by duncanhealy** [lmammino/realtime-transport-dashboards#1]
> START RequestId: c434fae1-cf6d-49e3-9bd6-8bc484053ea1 Version: $LATEST
> 
> 2019-10-01 13:49:22.518 (+01:00)	c434fae1-cf6d-49e3-9bd6-8bc484053ea1	ERROR	Invoke Error	{"errorType":"TypeError","errorMessage":"Cannot read property 'DocumentElement' of null","stack":["TypeError: Cannot read property 'DocumentElement' of null","    at Object.getRealTimeInfo (/var/task/node_modules/public-transport-ireland/dist/dublin-bus.js:14:64)","    at process._tickCallback (internal/process/next_tick.js:68:7)"]}
> END RequestId: c434fae1-cf6d-49e3-9bd6-8bc484053ea1
> REPORT RequestId: c434fae1-cf6d-49e3-9bd6-8bc484053ea1	Duration: 436.30 ms	Billed Duration: 500 ms	Memory Size: 1024 MB	Max Memory Used: 126 MB	Init Duration: 819.08 ms	

in external repo if bus station not found??

**Comment by lmammino** [comment]
Great finding @duncanhealy!

This should be fixed properly in the underlying library and this handler should manage errors a little bit better... I was lazy in both cases :P
